# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/devin/VGATest/VGATest.srcs/sources_1/ip/image_memory/image_memory.xci
# IP: The module: 'image_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/devin/VGATest/VGATest.gen/sources_1/ip/image_memory/image_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_memory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/devin/VGATest/VGATest.srcs/sources_1/ip/image_memory/image_memory.xci
# IP: The module: 'image_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/devin/VGATest/VGATest.gen/sources_1/ip/image_memory/image_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
