# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/devin/VGATest/VGATest.srcs/sources_1/ip/vgaCLKgen/vgaCLKgen.xci
# IP: The module: 'vgaCLKgen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/devin/VGATest/VGATest.gen/sources_1/ip/vgaCLKgen/vgaCLKgen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vgaCLKgen'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/devin/VGATest/VGATest.gen/sources_1/ip/vgaCLKgen/vgaCLKgen.xdc
# XDC: The top module name and the constraint reference have the same name: 'vgaCLKgen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/devin/VGATest/VGATest.gen/sources_1/ip/vgaCLKgen/vgaCLKgen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vgaCLKgen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/devin/VGATest/VGATest.gen/sources_1/ip/vgaCLKgen/vgaCLKgen_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'vgaCLKgen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/devin/VGATest/VGATest.srcs/sources_1/ip/vgaCLKgen/vgaCLKgen.xci
# IP: The module: 'vgaCLKgen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/devin/VGATest/VGATest.gen/sources_1/ip/vgaCLKgen/vgaCLKgen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vgaCLKgen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/devin/VGATest/VGATest.gen/sources_1/ip/vgaCLKgen/vgaCLKgen.xdc
# XDC: The top module name and the constraint reference have the same name: 'vgaCLKgen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/devin/VGATest/VGATest.gen/sources_1/ip/vgaCLKgen/vgaCLKgen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vgaCLKgen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/devin/VGATest/VGATest.gen/sources_1/ip/vgaCLKgen/vgaCLKgen_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'vgaCLKgen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
